# Generated by Django 3.2.11 on 2022-04-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_flipped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flipped',
        ),
    ]
