# Generated by Django 3.2.13 on 2024-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_delete_flipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomdiscussion',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizqa',
            name='option_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizqa',
            name='option_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizqa',
            name='option_3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizqa',
            name='option_4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizqa',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizqa',
            name='right_option',
            field=models.CharField(max_length=255),
        ),
    ]
