# Generated by Django 5.1.6 on 2025-02-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_rating'),
        ('staff', '0008_auto_20241001_1825'),
        ('student', '0018_flippeddiscussion_flippedreply'),
        ('suadmin', '0004_eventparticipants_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlippedDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_flipped_discussions', to='suadmin.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_flipped_discussions', to='student.student')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_flipped_discussions', to='account.profile')),
            ],
            options={
                'db_table': 'flipped_discussion',
            },
        ),
    ]
