# Generated by Django 5.1.6 on 2025-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_flippeddiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flippeddiscussion',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
