# Generated by Django 5.1.6 on 2025-02-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_flippeddiscussion_is_resolved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flippeddiscussion',
            old_name='is_resolved',
            new_name='resolve',
        ),
    ]
