# Generated by Django 5.1.6 on 2025-03-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_delete_flippeddiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ai_generation_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
