# Generated by Django 3.2.11 on 2022-01-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_quizqa'),
        ('account', '0001_initial'),
        ('student', '0003_studentquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('is_right', models.BooleanField()),
                ('coins', models.FloatField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.quizqa')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'student_quiz_questions',
            },
        ),
    ]
