# Generated by Django 3.2.11 on 2022-01-31 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('staff', '0004_classroomdiscussion'),
        ('student', '0004_studentquizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCRDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.FloatField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.classroomdiscussion')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'student_classroom_discussion',
            },
        ),
    ]
