# Generated by Django 3.2.11 on 2022-02-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_extracirricular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracirricular',
            old_name='extra_type',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='extracirricular',
            name='attendance',
        ),
    ]
