# Generated by Django 3.2.11 on 2022-04-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('staff', '0007_delete_flipped'),
        ('student', '0008_auto_20220228_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('coin', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile_flipped', to='account.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile_flipped', to='account.profile')),
            ],
            options={
                'db_table': 'flipped',
            },
        ),
    ]
