# Generated by Django 3.2.13 on 2022-04-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('staff', '0007_delete_flipped'),
        ('student', '0010_bestattendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestAttendance',
            new_name='BestPerfomer',
        ),
        migrations.AlterModelTable(
            name='bestperfomer',
            table='best_perfomer',
        ),
    ]
