# Generated by Django 3.2.13 on 2022-04-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_mytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
