# Generated by Django 3.2.13 on 2022-05-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipped',
            name='badge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
