# Generated by Django 3.2.13 on 2022-05-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_flipped_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
