# Generated by Django 3.2.13 on 2022-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesplayed',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesplayed',
            name='seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesplayed',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
